name: publish-nopcommerce-latest
on:
  workflow_dispatch:
  push:
    paths:
      - '**.nuspec'

jobs:
  build_and_pack:
    name: Build and Pack NopCommerce
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Build NopCommerce
        run: dotnet build --configuration Release
        working-directory: ./src/Presentation/Nop.Web.Framework

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --no-restore
        working-directory: ./src/Tests//Nop.Tests

      - name: Pack nopCommerce
        run: |
          dotnet pack ./src/Presentation/Nop.Web.Framework/Nop.Web.Framework.csproj --configuration Release /p:PackageOutputPath=$(pwd)/out /p:NuspecFile=../../NuGet/nop.web.framework.nuspec
          dotnet pack ./src/Libraries/Nop.Core/Nop.Core.csproj --configuration Release /p:PackageOutputPath=$(pwd)/out /p:NuspecFile=../../NuGet/nop.core.nuspec
          dotnet pack ./src/Libraries/Nop.Data/Nop.Data.csproj --configuration Release /p:PackageOutputPath=$(pwd)/out /p:NuspecFile=../../NuGet/nop.data.nuspec
          dotnet pack ./src/Libraries/Nop.Services/Nop.Services.csproj --configuration Release /p:PackageOutputPath=$(pwd)/out /p:NuspecFile=../../NuGet/nop.services.nuspec

      - name: Upload nopCommerce Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nopcommerce-nuget-package
          path: out/*nupkg
        
  publish_nuget_release:
    name: Publish to Nuget
    needs: build_and_pack
    runs-on: ubuntu-latest
    steps:
      - name: Download Nuget Packages
        uses: actions/download-artifact@v4
        with:
          name: nopcommerce-nuget-package
      
      - name: Publish Nuget Packages to Nuget
        run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
